/** Scene index retained for source integrity; type imports register no tests. */
export type ApplicationScenes = [
  typeof import('./application-short-status-saved.test.js'),
  typeof import('./application-account-binding.test.js'),
  typeof import('./application-login-qr-history.test.js'),
  typeof import('./application-chapter-read-owner.test.js'),
  typeof import('./application-chapter-draft-coverage.test.js'),
  typeof import('./application-chapter-directory-refresh.test.js'),
  typeof import('./application-book-metadata-maintenance.test.js'),
  typeof import('./application-job-account-isolation.test.js'),
  typeof import('./application-draft-creation-recovery.test.js'),
  typeof import('./application-creation-repair-conflicts.test.js'),
  typeof import('./application-metadata-dom-schema.test.js'),
  typeof import('./application-metadata-api-schema.test.js'),
  typeof import('./application-metrics-legacy-history.test.js'),
  typeof import('./application-metrics-fresh-history.test.js'),
  typeof import('./application-short-draft-directory.test.js'),
  typeof import('./application-short-draft-directory-history.test.js'),
  typeof import('./application-diagnostic-privacy-boundaries.test.js'),
  typeof import('./application-metrics-cutoff-facts.test.js'),
  typeof import('./application-write-capture-failures.test.js'),
  typeof import('./application-legacy-write-projections.test.js'),
  typeof import('./application-saved-audit-boundaries.test.js'),
];
