// Preserve the installed-source registration entry; scenarios register tests in their own files.
import type {} from './platform-reads-a-pending-long-management-replay-cannot-return-prior-works-after-mainframe-navigation-or-page-closure.test.js';
import type {} from './platform-reads-a-verified-volume-callback-or-an-outside-error-diagnostic-cannot-populate-incomplete-chapter-evidence-metadata.test.js';
import type {} from './platform-reads-api-authentication-expiration-clears-prior-records-rather-than-reporting-them-as-current.test.js';
import type {} from './platform-reads-blocked-draft-unknown-dynamic-paths-and-external-origins-never-retain-lowercase-title-token-segments-or-origin-values.test.js';
import type {} from './platform-reads-bootstrap-pending-within-document-still-rejects-foreign-routes-and-prior-violations-while-frozen-rules-remain-unchanged.test.js';
import type {} from './platform-reads-builtin-current-chapter-unit-keeps-exact-context-sources-and-current-raw-records-partial-under-one-fifo-slot.test.js';
import type {} from './platform-reads-cdp-initialization-retains-navigation-latches-across-its-frame-snapshot-and-cannot-adopt-duplicate-or-redirected-request-identities.test.js';
import type {} from './platform-reads-chapter-body-never-requests-absent-targets-or-unverified-owners-and-fails-a-single-response-without-retries-or-leaked-payload-aliases.test.js';
import type {} from './platform-reads-chapter-changed-parent-inventory-or-cross-volume-duplicate-cannot-report-complete-and-login-navigation-clears-rows.test.js';
import type {} from './platform-reads-chapter-diagnostic-cannot-treat-a-writer-shell-or-missing-old-and-foreign-natural-requests-as-ready-directory-data.test.js';
import type {} from './platform-reads-chapter-drafts-clear-all-records-on-parent-response-disposal-callback-or-late-cleanup-failure-and-hold-fifo-until-response-settles.test.js';
import type {} from './platform-reads-chapter-entry-uses-the-observed-id-title-binding-and-one-actual-read-button-emitting-no-private-values-or-guessed-chapter-schema.test.js';
import type {} from './platform-reads-chapter-sources-must-be-actual-current-gets-with-exact-parent-and-all-required-existing-pagination-keys.test.js';
import type {} from './platform-reads-chapter-static-pagination-and-volume-option-projection-exposes-only-bounded-structure-independently-of-generic-elements.test.js';
import type {} from './platform-reads-chapter-volume-observation-binds-the-validated-dom-nodes-across-reorder-and-rejects-replacement-status-or-detached-views-without-clicking-an.test.js';
import type {} from './platform-reads-collection-canonical-before-cannot-be-replaced-by-a-target-expected-identity-or-authenticated-page-cache.test.js';
import type {} from './platform-reads-collection-source-window-accepts-delayed-natural-gets-only-after-canonical-freeze-and-consumes-them-after-fresh-typed-owner-disposal.test.js';
import type {} from './platform-reads-context-navigation-telemetry-distinguishes-pending-commits-from-an-unpaired-same-url-bootstrap-commit-without-changing-the-failure.test.js';
import type {} from './platform-reads-current-account-get-replay-returns-only-selected-identity-and-query-free-evidence.test.js';
import type {} from './platform-reads-current-bootstrap-failure-metadata-remains-failure-only-and-never-replaces-the-original-reason-or-legacy-output.test.js';
import type {} from './platform-reads-current-canonical-fault-metadata-identifies-the-first-actually-rejecting-subcondition-without-executing-skipped-route-checks.test.js';
import type {} from './platform-reads-current-chapter-failure-metadata-distinguishes-each-identity-rejection-stage-using-only-local-type-observations.test.js';
import type {} from './platform-reads-current-login-diagnostic-returns-static-dom-router-structure-and-previously-observed-get-metadata-without-navigation-or-values.test.js';
import type {} from './platform-reads-distinct-phase-local-templates-and-unobserved-or-duplicate-fresh-requests-fail-closed-without-blind-retry.test.js';
import type {} from './platform-reads-draft-tab-readiness-has-one-non-renewing-local-deadline-inside-the-original-scope-deadline-and-cancels-its-temporary-listener.test.js';
import type {} from './platform-reads-draft-tab-spa-foreign-parent-route-changed-owner-and-a-tab-that-never-activates-remain-unavailable.test.js';
import type {} from './platform-reads-existing-diagnostic-tool-forwards-only-the-fixed-context-option-and-persists-independent-schema-metadata-without-chapter-promotion.test.js';
import type {} from './platform-reads-f03-cutoff-facts-fresh-missing-year-facts-are-accepted-old-inferred-basis-and-accessor-dtos-are-refused.test.js';
import type {} from './platform-reads-leased-stale-docker-singleton-links-recover-without-changing-authentication-or-story-storage.test.js';
import type {} from './platform-reads-long-metric-pagination-rejects-totals-duplicate-non-string-ids-and-missing-or-changed-list-field-types.test.js';
import type {} from './platform-reads-long-totals-duplicates-missing-string-ids-and-capped-pagination-cannot-certify-complete-coverage.test.js';
import type {} from './platform-reads-management-next-waits-cannot-cross-scope-deadlines-or-click-replaced-nodes-and-their-observations-are-revoked-by-late-failure.test.js';
import type {} from './platform-reads-observed-chapter-tabs-and-filters-expose-only-public-labels-active-flags-and-explicit-all-state-selection.test.js';
import type {} from './platform-reads-own-schema-diagnostic-replays-only-observed-no-target-own-sources-and-does-not-map-uid-as-account-identity.test.js';
import type {} from './platform-reads-post-external-unknown-and-prior-document-directory-responses-cannot-become-replayable-schema-sources.test.js';
import type {} from './platform-reads-profile-rename-followed-by-an-ancestor-symlink-at-the-final-lease-check-refuses-all-deletion.test.js';
import type {} from './platform-reads-read-diagnostic-replays-only-locally-observed-long-stats-get-urls-after-fresh-canonical-identity-despite-spa-cache-invalidation.test.js';
import type {} from './platform-reads-read-response-schema-is-restricted-to-observed-source-paths-and-emits-fixed-array-item-field-types-without-values.test.js';
import type {} from './platform-reads-short-management-fresh-pagination-keeps-original-tags-and-exact-official-publication-labels.test.js';
import type {} from './platform-reads-short-metadata-api-schema-fixed-descriptor-and-whole-safe-projection-reject-inconsistent-types-counts-and-fabricated-browser-proof.test.js';
import type {} from './platform-reads-short-metadata-api-schema-rejects-name-with-no-values-and-completed-cleanup.test.js';
import type {} from './platform-reads-short-metadata-schema-cancel-during-late-page-creation-closes-the-late-page-and-performs-no-navigation.test.js';
import type {} from './platform-reads-the-isolated-connected-cdp-epoch-accepts-explicit-same-url-within-document-proof-without-matching-public-events-or-global-identity-epoch.test.js';
import type {} from './platform-reads-the-observed-chapter-type-numeric-filter-survives-verified-spa-entry-source-validation-and-opaque-route-projection.test.js';
import type {} from './platform-reads-unknown-draft-resource-labels-stay-other-while-navigation-differentiates-grouped-observations-without-leaking-raw-labels.test.js';
import type {} from './platform-reads-volume-metadata-projects-fixed-keys-and-opaque-duplicate-parent-facts-without-url-or-any-query-value.test.js';
import type {} from './platform-reads-wrong-chapter-id-title-double-encoding-and-unknown-suffixes-never-register-or-inspect-a-landed-spa-directory.test.js';
export type { SourceObservationFixture } from './helpers/platform-reads-assert-context-probe-safe.js';
export type { ChapterFixtureSource } from './helpers/platform-reads-chapter-entry-fixture-work.js';
export type { ChapterStaticUiFixtureElement } from './helpers/platform-reads-chapter-entry-fixture-work.js';
export type { ChapterStaticUiFixture } from './helpers/platform-reads-chapter-entry-fixture-work.js';
export type { ChapterRenderReadinessFixture } from './helpers/platform-reads-chapter-entry-fixture-work.js';
export type { metadataSchema_ShortMetadataAliasFixture } from './helpers/platform-reads-current-chapter-body-fixture.js';
export type { ContextBlockedFixture } from './helpers/platform-reads-legacy-chapter-application-fixture.js';
export type { ContextOwnFixture } from './helpers/platform-reads-legacy-chapter-application-fixture.js';
export type { FixtureElement } from './helpers/platform-reads-metrics-page.js';
