/** Scene index retained for source integrity; type imports register no tests. */
export type TestScenes = [
  typeof import('./runtime-profile-recovery-lease-checks-succeed-only-while-this-store-is-open-and-owns-the-service.test.js'),
  typeof import('./runtime-a-whole-account-job-is-serialized-while-independent-accounts-can-run-together.test.js'),
  typeof import('./runtime-reconciliation-binds-later-live-read-target-operation-input-and-desired-content-before-durable-success.test.js'),
  typeof import('./runtime-running-write-cancellation-after-the-effect-boundary-is-uncertain-even-if-a-late-callback-returns-success.test.js'),
  typeof import('./runtime-login-error-after-the-write-boundary-remains-uncertain-instead-of-waiting-for-login.test.js'),
  typeof import('./runtime-creation-recovery-claims-exact-initial-allocation-once-and-rejects-changed-bindings-or-other-unknown-writes.test.js'),
  typeof import('./runtime-created-draft-repair-claim-binds-both-unknown-ancestors-and-refuses-unrelated-unknown-or-replacement-claimant.test.js'),
  typeof import('./runtime-created-draft-repair-successor-claims-preserve-the-exact-allocation-and-desired-request-and-reject-replacement-nonleaf-or-altered-unknown-an.test.js'),
  typeof import('./runtime-created-draft-repair-successor-closure-needs-the-complete-same-body-and-atomically-preserves-two-unknown-repair-ancestors-across-rollback-an.test.js'),
  typeof import('./runtime-created-draft-repair-successor-latest-unknown-alone-may-reconcile-and-close-after-same-key-restart-with-zero-or-one-historical-result.test.js'),
  typeof import('./runtime-c3-native-reconciliation-store-rejects-caller-resolution-and-malformed-fully-resigned-later-proofs.test.js'),
  typeof import('./runtime-c3-native-reconciliation-store-will-not-reuse-an-older-read-or-forged-continuation-prior-time.test.js'),
  typeof import('./runtime-server-compensation-private-registration-rejects-inputs-before-mutation-and-never-evaluates-accessors.test.js'),
  typeof import('./runtime-server-compensation-administrative-null-platform-registration-and-terminal-failed-audit-survive-restart.test.js'),
  typeof import('./runtime-server-compensation-saved-terminal-rejects-missing-aliased-or-forked-sql-and-registration-contexts-across-every-durable-exit.test.js'),
  typeof import('./runtime-task-summary-filters-before-its-256-row-cap-and-reports-exact-truncation.test.js'),
  typeof import('./runtime-r6-standalone-read-projects-literal-facts-and-actual-opaque-source-while-withholding-private-proof.test.js'),
  typeof import('./runtime-r6-absent-sql-observation-cannot-become-a-present-null-in-the-final-native-selector.test.js'),
  typeof import('./runtime-r6-live-repair-stores-four-actual-observations-and-closes-ancestors-only-after-full-verification.test.js'),
  typeof import('./runtime-r6-modern-create-pure-pre-allocation-failure-retains-null-target-and-unknown-null-publication-tuple.test.js'),
  typeof import('./runtime-r6-complete-same-target-other-root-ledger-audits-remain-disjoint-while-missing-head-or-partial-legacy-prefix-refuses-old-a.test.js'),
];
