// Preserve the installed-source registration entry; scenarios register tests in their own files.
import type {} from './short-native-body-api-body-api-production-gate-refuses-before-borrowing-or-creating-a-client.test.js';
import type {} from './short-native-body-api-body-durable-api-persists-actual-ordinal-one-graph-before-a-single-post-and-distinct-owner-cleanup-times.test.js';
import type {} from './short-native-body-api-body-durable-api-store-reconciliation-start-performs-only-fresh-after-get-and-never-issues-an-attempt.test.js';
import type {} from './short-native-body-api-body-fixture-lease-abort-deadline-and-late-context-keep-cleanup-ownership.test.js';
import type {} from './short-native-body-api.test.js';
import type {} from './short-native-body-browser.test.js';
import type {} from './short-native-body-duplicate-nonempty-unknown-and-contradictory-marker-attributes-are-rejected.test.js';
import type {} from './short-native-body-full-unknown-metadata-titles-category-cover-and-catalog-retention-is-required.test.js';
import type {} from './short-native-body-integration-body-integration-app-partial-live-retrieval-stays-incomplete-while-historical-closure-stays-saved.test.js';
import type {} from './short-native-body-integration-body-integration-inherited-owned-browser-and-real-queue-persist-seven-stage-fixture-graph-once.test.js';
import type {} from './short-native-body-integration.test.js';
import type {} from './short-native-body-o01-raw-entity-three-br-token-byte-round-trip.test.js';
import type {} from './short-native-body-owned-recovery-store.test.js';
import type {} from './short-native-body-proof-body-durable-proof-partial-immutable-closure-later-matching-and-historical-pointers-preserve-unknown.test.js';
import type {} from './short-native-body-proof-body-explicit-read-projection-actual-sql-physical-context-emits-only-paragraph-provenance-and-fixed-hashes.test.js';
import type {} from './short-native-body-proof-body-explicit-read-projection-marker-boundary-and-fresh-source-indices-cannot-splice-separate-saved-graphs.test.js';
import type {} from './short-native-body-proof-body-fixture-proof-descriptor-only-shapes-and-every-fabricated-live-authority-fail-without-getters.test.js';
import type {} from './short-native-body-proof-body-fixture-proof-exact-exports-datasets-fixed-basis-digest-and-immutable-stage-dto.test.js';
import type {} from './short-native-body-proof.test.js';
import type {} from './short-native-body-public-body-public-authentication-and-no-store-protect-explicit-body-response.test.js';
import type {} from './short-native-body-public-body-public-fixture-constructor-cannot-prove-live-or-fall-back-to-default-transport.test.js';
import type {} from './short-native-body-public-body-public-process-death-after-committed-attempt-recovers-unknown-without-replay.test.js';
import type {} from './short-native-body-public-body-public-sdk-lists-exact-strict-read-and-write-schemas.test.js';
import type {} from './short-native-body-public-body-public-sdk-save-creates-one-real-sql-attempt-and-seven-stage-graph.test.js';
import type {} from './short-native-body-public.test.js';
import type {} from './short-native-body-reconciliation-fence.test.js';
import type {} from './short-native-body-store-body-store-native-body-markers-take-priority-over-legal-trial-fields-and-mixed-generic-completions.test.js';
import type {} from './short-native-body-store-body-store-opaque-issuance-is-tied-to-genuine-leased-construction-and-constructor-policy.test.js';
import type {} from './short-native-body-store.test.js';
import type {} from './short-native-body-word-number-derived-word-number-v2-accepts-exact-official-500-to-600-without-redefining-legacy-v1.test.js';
import type {} from './short-native-body-word-number.test.js';
export type { Faults } from './helpers/short-native-body-api-edit.js';
export type { RawFixture } from './helpers/short-native-body-fixture.js';
export type { Data } from './helpers/short-native-body-proof-utf16.js';
export type { Stage } from './helpers/short-native-body-proof-utf16.js';
export type { Trace } from './helpers/short-native-body-proof-utf16.js';
export type { FixtureOptions } from './helpers/short-native-body-public-account.js';
export type { BrowserInternals } from './helpers/short-native-body-public-account.js';
