import { type AssertAccountUsableOperation } from './contracts/assert-account-usable.js';
import { type IsCurrentPageSlotOperation } from './contracts/is-current-page-slot.js';
import { type OwnsPageSlotOperation } from './contracts/owns-page-slot.js';
import { type ObserveIdentityOperation } from './contracts/observe-identity.js';
import { type RememberIdentityOperation } from './contracts/remember-identity.js';
import { type EnsurePageOperation } from './contracts/ensure-page.js';
import { type WithPageOperation } from './contracts/with-page.js';
import { type DiagnoseShortMetadataSchemaOperation } from './contracts/diagnose-short-metadata-schema.js';
import { type DiagnoseShortMetadataApiSchemaOperation } from './contracts/diagnose-short-metadata-api-schema.js';
import { type RunShortDraftDirectoryOperation } from './contracts/run-short-draft-directory.js';
import { type RunNativeShortMetadataOperation } from './contracts/run-native-short-metadata.js';
import { type RunNativeShortMetadataUpdateOperation } from './contracts/run-native-short-metadata-update.js';
import { type RunNativeShortCoverUpdateOperation } from './contracts/run-native-short-cover-update.js';
import { type RunNativeShortTrialUpdateOperation } from './contracts/run-native-short-trial-update.js';
import { type RunNativeShortSubmissionOperation } from './contracts/run-native-short-submission.js';
import { type RunNativeShortSubmissionFixtureOperation } from './contracts/run-native-short-submission-fixture.js';
import { type RunNativeShortSubmissionOwnedOperation } from './contracts/run-native-short-submission-owned.js';
import { type RunNativeShortBodyUpdateOperation } from './contracts/run-native-short-body-update.js';
import { type RunNativeShortBodyFixtureUpdateOperation } from './contracts/run-native-short-body-fixture-update.js';
import { type RunNativeShortBodyOwnedOperation } from './contracts/run-native-short-body-owned.js';
import { type ReadOperation } from './contracts/read.js';
import { type InspectLoginOperation } from './contracts/inspect-login.js';
import { type CheckLoginOperation } from './contracts/check-login.js';
import { type StartLoginOperation } from './contracts/start-login.js';
import { type InspectCurrentLoginOperation } from './contracts/inspect-current-login.js';
import { type DiagnoseCurrentLoginPageOperation } from './contracts/diagnose-current-login-page.js';
import { type ReadLoginQrUiOperation } from './contracts/read-login-qr-ui.js';
import { type GetLoginQrcodeOperation } from './contracts/get-login-qrcode.js';
import { type ScreenshotOperation } from './contracts/screenshot.js';
import { type VerifyCurrentAccountOperation } from './contracts/verify-current-account.js';
import { type WaitForWriterReadyOperation } from './contracts/wait-for-writer-ready.js';
import { type WaitForObservedOwnSourceOperation } from './contracts/wait-for-observed-own-source.js';
import { type EnterCurrentChapterDirectoryOperation } from './contracts/enter-current-chapter-directory.js';
import { type OpenExistingChapterDirectoryOperation } from './contracts/open-existing-chapter-directory.js';
import { type OpenChapterDraftTabOperation } from './contracts/open-chapter-draft-tab.js';
import { type CollectCurrentChapterDirectoryOperation } from './contracts/collect-current-chapter-directory.js';
import { type CollectCurrentChapterBodyOperation } from './contracts/collect-current-chapter-body.js';
import { type CollectChapterDirectoryReadOperation } from './contracts/collect-chapter-directory-read.js';
import { type CollectCurrentChapterDraftDirectoryOperation } from './contracts/collect-current-chapter-draft-directory.js';
import { type OpenOwnedChapterDraftTabOperation } from './contracts/open-owned-chapter-draft-tab.js';
import { type ReadCurrentChapterDraftContextOperation } from './contracts/read-current-chapter-draft-context.js';
import { type DiagnoseChapterVolumeContextOperation } from './contracts/diagnose-chapter-volume-context.js';
import { type ReadCurrentChapterContextOperation } from './contracts/read-current-chapter-context.js';
import { type PrepareChapterDiagnosticOperation } from './contracts/prepare-chapter-diagnostic.js';
import { type DiagnoseReadPageOperation } from './contracts/diagnose-read-page.js';
import { type CloseOperation } from './contracts/close.js';
export interface BrowserOperations {
  assertAccountUsable: AssertAccountUsableOperation;
  isCurrentPageSlot: IsCurrentPageSlotOperation;
  ownsPageSlot: OwnsPageSlotOperation;
  observeIdentity: ObserveIdentityOperation;
  rememberIdentity: RememberIdentityOperation;
  ensurePage: EnsurePageOperation;
  withPage: WithPageOperation;
  diagnoseShortMetadataSchema: DiagnoseShortMetadataSchemaOperation;
  diagnoseShortMetadataApiSchema: DiagnoseShortMetadataApiSchemaOperation;
  runShortDraftDirectory: RunShortDraftDirectoryOperation;
  runNativeShortMetadata: RunNativeShortMetadataOperation;
  runNativeShortMetadataUpdate: RunNativeShortMetadataUpdateOperation;
  runNativeShortCoverUpdate: RunNativeShortCoverUpdateOperation;
  runNativeShortTrialUpdate: RunNativeShortTrialUpdateOperation;
  runNativeShortSubmission: RunNativeShortSubmissionOperation;
  runNativeShortSubmissionFixture: RunNativeShortSubmissionFixtureOperation;
  runNativeShortSubmissionOwned: RunNativeShortSubmissionOwnedOperation;
  runNativeShortBodyUpdate: RunNativeShortBodyUpdateOperation;
  runNativeShortBodyFixtureUpdate: RunNativeShortBodyFixtureUpdateOperation;
  runNativeShortBodyOwned: RunNativeShortBodyOwnedOperation;
  read: ReadOperation;
  inspectLogin: InspectLoginOperation;
  checkLogin: CheckLoginOperation;
  startLogin: StartLoginOperation;
  inspectCurrentLogin: InspectCurrentLoginOperation;
  diagnoseCurrentLoginPage: DiagnoseCurrentLoginPageOperation;
  readLoginQrUi: ReadLoginQrUiOperation;
  getLoginQrcode: GetLoginQrcodeOperation;
  screenshot: ScreenshotOperation;
  verifyCurrentAccount: VerifyCurrentAccountOperation;
  waitForWriterReady: WaitForWriterReadyOperation;
  waitForObservedOwnSource: WaitForObservedOwnSourceOperation;
  enterCurrentChapterDirectory: EnterCurrentChapterDirectoryOperation;
  openExistingChapterDirectory: OpenExistingChapterDirectoryOperation;
  openChapterDraftTab: OpenChapterDraftTabOperation;
  collectCurrentChapterDirectory: CollectCurrentChapterDirectoryOperation;
  collectCurrentChapterBody: CollectCurrentChapterBodyOperation;
  collectChapterDirectoryRead: CollectChapterDirectoryReadOperation;
  collectCurrentChapterDraftDirectory: CollectCurrentChapterDraftDirectoryOperation;
  openOwnedChapterDraftTab: OpenOwnedChapterDraftTabOperation;
  readCurrentChapterDraftContext: ReadCurrentChapterDraftContextOperation;
  diagnoseChapterVolumeContext: DiagnoseChapterVolumeContextOperation;
  readCurrentChapterContext: ReadCurrentChapterContextOperation;
  prepareChapterDiagnostic: PrepareChapterDiagnosticOperation;
  diagnoseReadPage: DiagnoseReadPageOperation;
  close: CloseOperation;
}
