// Exact public reference set independently audited on 2026-10-04; closure remains incomplete.
export const SHORT_METADATA_ASSETS: ReadonlyArray<readonly [string, 'script' | 'stylesheet']> = [
  ['https://ipolyfill-origin.bytedance.com/0.0.19/polyfill.min.js', 'script'],
  ['https://lf-c-flwb.bytetos.com/obj/rc-client-security/web/glue/1.0.0.65/sdk-glue.js', 'script'],
  ['https://lf-security.bytegoofy.com/obj/security-secsdk/runtime.js', 'script'],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/1999.874733e9.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/2059.988f9800.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/2292.3770e47e.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/2630.9b7c0aca.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/2930.d1ed9133.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/3055.7071f09a.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/3306.c26c4554.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/414.929df8aa.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/4400.a66bb898.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/4896.a96c237a.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/5182.0709e71b.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/6974.63ebaf05.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/7460.169042fe.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/7751.51109701.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/7776.0df52467.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/8584.cb0a062c.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/9044.657efde7.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/9253.8bfc56a7.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/PublishShort.682f6eac.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/async-main.b48765da.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/css/async/debugger.4576f597.css',
    'stylesheet',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/5526.35de1fdd.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/1254.6674de6b.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/1734.0aa675f0.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/1824.8017e321.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/2292.b7cb6e06.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/2630.79524422.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/2855.75a4890b.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/2930.3e4f7fff.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/3055.d6ce8a95.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/3260.e2050501.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/3306.a366c0e9.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/3756.7fdc6c64.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/4070.8e6a5d28.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/4245.1bc35cc3.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/4274.3dc0c07f.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/4392.1fd2afbb.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/4405.d1b31d2d.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/4559.51a10b76.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/4615.9205ea55.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/496.42393dae.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/5000.1514ee84.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/5182.7697f0f6.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/5194.c88a6fe5.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/526.b9723857.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/5477.07a54120.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/5873.3ff27887.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/5989.3fa85007.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/609.2598ce5f.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/6840.717784f3.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/6974.e6303a67.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/7023.7bcce589.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/75.06988366.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/7751.7514d46e.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/7885.5769f43d.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/8200.5448e0f2.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/8756.a0023436.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/8816.398f3f9a.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/8974.32080a41.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9044.040a2983.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9068.0ef9d1d1.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9077.4ce6f9a8.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9253.af865acd.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9396.1f779e52.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9714.3434f4ed.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/974.85779776.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9800.29c99756.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9857.6ba072c3.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/9878.b66cf314.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/PublishShort.4c89ddd6.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/async-main.93c6ad0a.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/debugger.bc824756.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/lib-axios.97e92b34.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/async/lib-router.b6c5afa9.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/muye/main/static/js/main.c1caeb5e.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/novel_fe/serial_common_vmok/static/js/async/191.3f92879d.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/novel_fe/serial_common_vmok/static/js/async/682.18d6e529.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/novel_fe/serial_common_vmok/static/js/async/__federation_expose_common_provider.c2a19801.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/novel_fe/serial_common_vmok/static/js/lib-polyfill.05b3766b.js',
    'script',
  ],
  [
    'https://lf-serial-static.fanqienovel.com/obj/novel-serial-cdn/toutiao/novel_fe/serial_common_vmok/vmok-remote-entry.5e16a9a0.js',
    'script',
  ],
  ['https://lf1-cdn-tos.bytegoofy.com/obj/goofy/secsdk/secsdk-lastest.umd.js', 'script'],
  ['https://privacy.zijieapi.com/api/web-cmp/sdk/?project_key=80b920d966da0f81', 'script'],
];
