import {
  type WithPublicProjectionReadOperation,
  type MemoPublicProjectionOperation,
  type AssertPublicReadEntryAllowedOperation,
  type AssertPublicReadMutationAllowedOperation,
  type BindExistingSqlReadOperation,
  type RawAccountAttemptRowsOperation,
  type DecodeJobOperation,
  type RawJobOperation,
  type GetJobOperation,
  type ListKnownWriteTaskSummariesOperation,
  type ListJobsOperation,
  type GetJobForPublicProjectionOperation,
  type ListJobsForPublicProjectionOperation,
  type FindIdempotentOperation,
  type CreateJobOperation,
  type RunningJobOperation,
  type StartJobOperation,
  type AssertNotCancelledOperation,
  type RequestCancellationOperation,
  type MarkPlatformReadStartedOperation,
  type MarkPlatformWriteStartedOperation,
  type ListNativeShortBodyAttemptsOperation,
  type PersistNativeShortBodyStageOperation,
  type GetNativeShortBodyRecoveryContextOperation,
  type IssueNativeShortBodyWriteAuthorityOperation,
  type IssueNativeShortBodyReconciliationAuthorityOperation,
  type CreateNativeShortBodyAuthorityOperation,
  type ValidateNativeShortBodyHistoryOperation,
  type GetNativeShortBodyOriginalAuditOperation,
  type ValidateNativeShortBodyJobOperation,
  type ReconcileNativeShortBodyWriteOperation,
  type GetNativeShortSubmissionPreparationOperation,
  type ListNativeShortSubmissionAttemptsOperation,
  type RecordNativeShortSubmissionAttemptOperation,
  type ListNativeShortTrialAttemptsOperation,
  type RecordNativeShortTrialAttemptOperation,
  type ListNativeShortCoverAttemptsOperation,
  type RecordNativeShortCoverAttemptOperation,
  type AddJobMetadataOperation,
  type RecordTargetOperation,
  type CompleteReadJobOperation,
  type CompleteWriteJobOperation,
  type FailJobOperation,
  type RecoverInterruptedOperation,
  type ResolveOperatorEntryInvestigationOperation,
  type NativeRegistrationSignalOperation,
  type NativeRegistrationRowsOperation,
  type ValidateNativeRegistrationJobOperation,
  type NativeLaterReadOperation,
  type AssertNativeLiveSettlementOperation,
  type ValidateNativeReconciliationRowOperation,
  type ValidateNativeClosureOperation,
  type ReconcileNativeShortWriteOperation,
  type ValidateNativeShortSubmissionHistoryOperation,
  type GetNativeShortSubmissionOriginalAuditOperation,
  type AssertNativeShortSubmissionLiveSettlementOperation,
} from './contracts/jobs-api-with-public-projection-read.js';

import {
  type RunLeaseLossCleanupOperation,
  type PrepareOperation,
  type EnsureOpenOperation,
  type HasLostServiceLeaseOperation,
  type OnServiceLeaseLostOperation,
  type DeliverLeaseLossOperation,
  type LoseOwnershipOperation,
  type LostLeaseErrorOperation,
  type AssertOwnershipOperation,
  type AssertLeaseOwnershipOperation,
  type TransactionOperation,
  type RenewLeaseOperation,
  type CloseOperation,
  type PrepareNativeShortBodyReconciliationOperation,
  type PreparePhysicalEvidenceOperation,
} from './contracts/runtime-ownership-run-lease-loss-cleanup.js';
import {
  type PublicEvidenceFileSizeOperation,
  type BindEvidenceReadOperation,
  type PrefetchPublicRowsOperation,
  type EnsurePublicEvidenceIndexOperation,
  type SaveEvidenceOperation,
  type InsertPhysicalEvidenceOperation,
  type ListEvidenceOperation,
  type ReadEvidenceOperation,
  type ReadEvidenceFreshOperation,
  type NativeBoundedReferencesOperation,
  type NativeOriginalEvidenceOperation,
  type GetManifestForJobOperation,
} from './contracts/evidence-public-evidence-file-size.js';

import {
  type NativeShortBodySignalOperation,
  type NativeShortBodyContextOperation,
  type NativeShortBodyStageOperation,
  type NativeShortBodyIssuerOperation,
  type NativeShortBodyRecoveryFreshReadOperation,
  type NativeShortBodyRecoveryFromPayloadOperation,
  type NativeShortBodyReconciliationRowsOperation,
  type NativeShortBodyLaterReadOperation,
  type NativeShortBodySettlementErrorOperation,
} from './contracts/native-body-native-short-body-signal.js';

import {
  type NativeShortSubmissionContextOperation,
  type NativeShortTrialContextOperation,
  type NativeShortCoverContextOperation,
  type NativeShortSubmissionSettlementErrorOperation,
  type NativeShortSubmissionLaterReadOperation,
  type NativeShortTrialSettlementErrorOperation,
  type NativeShortTrialLaterReadOperation,
  type NativeShortCoverSettlementErrorOperation,
  type NativeShortCoverLaterReadOperation,
} from './contracts/native-states-native-short-submission-context.js';

import {
  type GenericRefsOperation,
  type GenericRawNodeOperation,
  type GenericReadGraphOperation,
  type CaptureGenericShortPublicationGraphOperation,
  type RereadGenericShortPublicationGraphOperation,
  type GenericWitnessOperation,
  type GenericPointerOperation,
  type GenericPrefixOperation,
  type GenericSettlementErrorOperation,
  type GenericModernObservationsOperation,
  type GenericHistoricalOperation,
  type GenericLegacySnapshotOperation,
  type GenericReadCompleteOperation,
  type GenericRootAnchorOperation,
  type GenericAuditPriorOperation,
  type GenericValidateAuditOperation,
  type GenericLedgerOperation,
  type GenericQualifyWriteOperation,
  type GenericEffectHistoryOperation,
  type GenericAssociationOperation,
  type GenericUnobservedReadOperation,
  type GenericSelectOperation,
  type GenericTupleOperation,
  type GenericMutationGraphOperation,
  type GetGenericShortOriginalAuditOperation,
  type GenericReadFailureOperation,
  type GenericShortPublicationOperation,
  type GenericShortEvidenceRowsOperation,
  type GenericShortProjectionOperation,
  type GenericShortCreationEventProjectionOperation,
  type GenericShortPublicJobOperation,
} from './contracts/generic-status-generic-refs.js';

import {
  type GenericCreationPriorOperation,
  type GenericCreationPriorViewOperation,
  type GenericCreationEnvelopeInGraphOperation,
  type GenericCreationUnknownOperation,
  type GenericCreationResumeClaimOperation,
  type GenericCreationAncestorOperation,
  type GenericCreationOpenFamilyOperation,
  type GenericCreationEventAssociationsOperation,
  type GenericCreationEventOperation,
  type GenericCreationEnvelopeOperation,
  type GenericRepairEntryOperation,
  type GetCreationRepairSuccessorOperation,
  type CreationRepairJobsOperation,
  type CreationRepairPriorOperation,
  type GetCreationRepairAncestorIdsOperation,
  type VerifyUnknownRepairChainOperation,
  type GetCreationRepairOperation,
  type ClaimCreationRepairOperation,
  type CompleteCreationRepairOperation,
} from './contracts/creation-recovery-generic-creation-prior.js';

import {
  type ValidateNativeCompensationSourceIdentityOperation,
  type ValidateNativeCompensationInstalledSourceOperation,
  type NativeCompensationSourceOperation,
  type GetNativeCompensationContextOperation,
  type RegisterNativeCompensationAttestationOperation,
  type ValidateNativeCompensatedClosureOperation,
  type ReconcileNativeCompensationOperation,
  type NativeReconciliationRowOperation,
} from './contracts/native-compensation-validate-native-compensation-source-identity.js';

import {
  type ReconcileNativeShortSubmissionWriteOperation,
  type ValidateNativeShortTrialHistoryOperation,
  type GetNativeShortTrialOriginalAuditOperation,
  type AssertNativeShortTrialLiveSettlementOperation,
  type ReconcileNativeShortTrialWriteOperation,
  type ValidateNativeShortCoverHistoryOperation,
  type GetNativeShortCoverOriginalAuditOperation,
  type AssertNativeShortCoverLiveSettlementOperation,
  type ReconcileNativeShortCoverWriteOperation,
  type ReconcileWriteJobOperation,
  type GetCreationRecoveryOperation,
  type ClaimCreationRecoveryOperation,
  type CompleteCreationRecoveryOperation,
  type GetCurrentOperation,
  type HistoryOperation,
} from './contracts/jobs-api-reconcile-native-short-submission-write.js';

export interface StoreOperations {
  withPublicProjectionRead: WithPublicProjectionReadOperation;
  memoPublicProjection: MemoPublicProjectionOperation;
  assertPublicReadEntryAllowed: AssertPublicReadEntryAllowedOperation;
  assertPublicReadMutationAllowed: AssertPublicReadMutationAllowedOperation;
  runLeaseLossCleanup: RunLeaseLossCleanupOperation;
  publicEvidenceFileSize: PublicEvidenceFileSizeOperation;
  bindExistingSqlRead: BindExistingSqlReadOperation;
  bindEvidenceRead: BindEvidenceReadOperation;
  prepare: PrepareOperation;
  rawAccountAttemptRows: RawAccountAttemptRowsOperation;
  prefetchPublicRows: PrefetchPublicRowsOperation;
  ensurePublicEvidenceIndex: EnsurePublicEvidenceIndexOperation;
  ensureOpen: EnsureOpenOperation;
  hasLostServiceLease: HasLostServiceLeaseOperation;
  onServiceLeaseLost: OnServiceLeaseLostOperation;
  deliverLeaseLoss: DeliverLeaseLossOperation;
  loseOwnership: LoseOwnershipOperation;
  lostLeaseError: LostLeaseErrorOperation;
  assertOwnership: AssertOwnershipOperation;
  assertLeaseOwnership: AssertLeaseOwnershipOperation;
  transaction: TransactionOperation;
  renewLease: RenewLeaseOperation;
  close: CloseOperation;
  decodeJob: DecodeJobOperation;
  rawJob: RawJobOperation;
  getJob: GetJobOperation;
  listKnownWriteTaskSummaries: ListKnownWriteTaskSummariesOperation;
  listJobs: ListJobsOperation;
  getJobForPublicProjection: GetJobForPublicProjectionOperation;
  listJobsForPublicProjection: ListJobsForPublicProjectionOperation;
  findIdempotent: FindIdempotentOperation;
  createJob: CreateJobOperation;
  runningJob: RunningJobOperation;
  startJob: StartJobOperation;
  assertNotCancelled: AssertNotCancelledOperation;
  requestCancellation: RequestCancellationOperation;
  markPlatformReadStarted: MarkPlatformReadStartedOperation;
  markPlatformWriteStarted: MarkPlatformWriteStartedOperation;
  nativeShortBodySignal: NativeShortBodySignalOperation;
  listNativeShortBodyAttempts: ListNativeShortBodyAttemptsOperation;
  nativeShortBodyContext: NativeShortBodyContextOperation;
  nativeShortBodyStage: NativeShortBodyStageOperation;
  persistNativeShortBodyStage: PersistNativeShortBodyStageOperation;
  nativeShortBodyIssuer: NativeShortBodyIssuerOperation;
  nativeShortBodyRecoveryFreshRead: NativeShortBodyRecoveryFreshReadOperation;
  nativeShortBodyRecoveryFromPayload: NativeShortBodyRecoveryFromPayloadOperation;
  getNativeShortBodyRecoveryContext: GetNativeShortBodyRecoveryContextOperation;
  prepareNativeShortBodyReconciliation: PrepareNativeShortBodyReconciliationOperation;
  issueNativeShortBodyWriteAuthority: IssueNativeShortBodyWriteAuthorityOperation;
  issueNativeShortBodyReconciliationAuthority: IssueNativeShortBodyReconciliationAuthorityOperation;
  nativeShortBodyReconciliationRows: NativeShortBodyReconciliationRowsOperation;
  createNativeShortBodyAuthority: CreateNativeShortBodyAuthorityOperation;
  nativeShortBodyLaterRead: NativeShortBodyLaterReadOperation;
  nativeShortBodySettlementError: NativeShortBodySettlementErrorOperation;
  validateNativeShortBodyHistory: ValidateNativeShortBodyHistoryOperation;
  getNativeShortBodyOriginalAudit: GetNativeShortBodyOriginalAuditOperation;
  validateNativeShortBodyJob: ValidateNativeShortBodyJobOperation;
  reconcileNativeShortBodyWrite: ReconcileNativeShortBodyWriteOperation;
  getNativeShortSubmissionPreparation: GetNativeShortSubmissionPreparationOperation;
  listNativeShortSubmissionAttempts: ListNativeShortSubmissionAttemptsOperation;
  nativeShortSubmissionContext: NativeShortSubmissionContextOperation;
  recordNativeShortSubmissionAttempt: RecordNativeShortSubmissionAttemptOperation;
  listNativeShortTrialAttempts: ListNativeShortTrialAttemptsOperation;
  nativeShortTrialContext: NativeShortTrialContextOperation;
  recordNativeShortTrialAttempt: RecordNativeShortTrialAttemptOperation;
  listNativeShortCoverAttempts: ListNativeShortCoverAttemptsOperation;
  nativeShortCoverContext: NativeShortCoverContextOperation;
  recordNativeShortCoverAttempt: RecordNativeShortCoverAttemptOperation;
  genericRefs: GenericRefsOperation;
  genericRawNode: GenericRawNodeOperation;
  genericReadGraph: GenericReadGraphOperation;
  captureGenericShortPublicationGraph: CaptureGenericShortPublicationGraphOperation;
  rereadGenericShortPublicationGraph: RereadGenericShortPublicationGraphOperation;
  genericWitness: GenericWitnessOperation;
  genericPointer: GenericPointerOperation;
  genericPrefix: GenericPrefixOperation;
  genericSettlementError: GenericSettlementErrorOperation;
  genericModernObservations: GenericModernObservationsOperation;
  genericHistorical: GenericHistoricalOperation;
  genericLegacySnapshot: GenericLegacySnapshotOperation;
  genericReadComplete: GenericReadCompleteOperation;
  genericRootAnchor: GenericRootAnchorOperation;
  genericAuditPrior: GenericAuditPriorOperation;
  genericValidateAudit: GenericValidateAuditOperation;
  genericLedger: GenericLedgerOperation;
  genericQualifyWrite: GenericQualifyWriteOperation;
  genericEffectHistory: GenericEffectHistoryOperation;
  genericAssociation: GenericAssociationOperation;
  genericUnobservedRead: GenericUnobservedReadOperation;
  genericSelect: GenericSelectOperation;
  genericCreationPrior: GenericCreationPriorOperation;
  genericCreationPriorView: GenericCreationPriorViewOperation;
  genericCreationEnvelopeInGraph: GenericCreationEnvelopeInGraphOperation;
  genericCreationUnknown: GenericCreationUnknownOperation;
  genericCreationResumeClaim: GenericCreationResumeClaimOperation;
  genericCreationAncestor: GenericCreationAncestorOperation;
  genericCreationOpenFamily: GenericCreationOpenFamilyOperation;
  genericCreationEventAssociations: GenericCreationEventAssociationsOperation;
  genericCreationEvent: GenericCreationEventOperation;
  genericTuple: GenericTupleOperation;
  genericMutationGraph: GenericMutationGraphOperation;
  getGenericShortOriginalAudit: GetGenericShortOriginalAuditOperation;
  genericReadFailure: GenericReadFailureOperation;
  genericShortPublication: GenericShortPublicationOperation;
  genericShortEvidenceRows: GenericShortEvidenceRowsOperation;
  genericShortProjection: GenericShortProjectionOperation;
  genericShortCreationEventProjection: GenericShortCreationEventProjectionOperation;
  genericShortPublicJob: GenericShortPublicJobOperation;
  addJobMetadata: AddJobMetadataOperation;
  recordTarget: RecordTargetOperation;
  saveEvidence: SaveEvidenceOperation;
  preparePhysicalEvidence: PreparePhysicalEvidenceOperation;
  insertPhysicalEvidence: InsertPhysicalEvidenceOperation;
  listEvidence: ListEvidenceOperation;
  readEvidence: ReadEvidenceOperation;
  readEvidenceFresh: ReadEvidenceFreshOperation;
  completeReadJob: CompleteReadJobOperation;
  completeWriteJob: CompleteWriteJobOperation;
  failJob: FailJobOperation;
  recoverInterrupted: RecoverInterruptedOperation;
  resolveOperatorEntryInvestigation: ResolveOperatorEntryInvestigationOperation;
  validateNativeCompensationSourceIdentity: ValidateNativeCompensationSourceIdentityOperation;
  validateNativeCompensationInstalledSource: ValidateNativeCompensationInstalledSourceOperation;
  nativeBoundedReferences: NativeBoundedReferencesOperation;
  nativeRegistrationSignal: NativeRegistrationSignalOperation;
  nativeRegistrationRows: NativeRegistrationRowsOperation;
  nativeCompensationSource: NativeCompensationSourceOperation;
  getNativeCompensationContext: GetNativeCompensationContextOperation;
  validateNativeRegistrationJob: ValidateNativeRegistrationJobOperation;
  registerNativeCompensationAttestation: RegisterNativeCompensationAttestationOperation;
  validateNativeCompensatedClosure: ValidateNativeCompensatedClosureOperation;
  reconcileNativeCompensation: ReconcileNativeCompensationOperation;
  nativeReconciliationRow: NativeReconciliationRowOperation;
  nativeLaterRead: NativeLaterReadOperation;
  nativeOriginalEvidence: NativeOriginalEvidenceOperation;
  assertNativeLiveSettlement: AssertNativeLiveSettlementOperation;
  validateNativeReconciliationRow: ValidateNativeReconciliationRowOperation;
  validateNativeClosure: ValidateNativeClosureOperation;
  reconcileNativeShortWrite: ReconcileNativeShortWriteOperation;
  nativeShortSubmissionSettlementError: NativeShortSubmissionSettlementErrorOperation;
  nativeShortSubmissionLaterRead: NativeShortSubmissionLaterReadOperation;
  validateNativeShortSubmissionHistory: ValidateNativeShortSubmissionHistoryOperation;
  getNativeShortSubmissionOriginalAudit: GetNativeShortSubmissionOriginalAuditOperation;
  assertNativeShortSubmissionLiveSettlement: AssertNativeShortSubmissionLiveSettlementOperation;
  reconcileNativeShortSubmissionWrite: ReconcileNativeShortSubmissionWriteOperation;
  nativeShortTrialSettlementError: NativeShortTrialSettlementErrorOperation;
  nativeShortTrialLaterRead: NativeShortTrialLaterReadOperation;
  validateNativeShortTrialHistory: ValidateNativeShortTrialHistoryOperation;
  getNativeShortTrialOriginalAudit: GetNativeShortTrialOriginalAuditOperation;
  assertNativeShortTrialLiveSettlement: AssertNativeShortTrialLiveSettlementOperation;
  reconcileNativeShortTrialWrite: ReconcileNativeShortTrialWriteOperation;
  nativeShortCoverSettlementError: NativeShortCoverSettlementErrorOperation;
  nativeShortCoverLaterRead: NativeShortCoverLaterReadOperation;
  validateNativeShortCoverHistory: ValidateNativeShortCoverHistoryOperation;
  getNativeShortCoverOriginalAudit: GetNativeShortCoverOriginalAuditOperation;
  assertNativeShortCoverLiveSettlement: AssertNativeShortCoverLiveSettlementOperation;
  reconcileNativeShortCoverWrite: ReconcileNativeShortCoverWriteOperation;
  reconcileWriteJob: ReconcileWriteJobOperation;
  getCreationRecovery: GetCreationRecoveryOperation;
  genericCreationEnvelope: GenericCreationEnvelopeOperation;
  genericRepairEntry: GenericRepairEntryOperation;
  claimCreationRecovery: ClaimCreationRecoveryOperation;
  completeCreationRecovery: CompleteCreationRecoveryOperation;
  getCreationRepairSuccessor: GetCreationRepairSuccessorOperation;
  creationRepairJobs: CreationRepairJobsOperation;
  creationRepairPrior: CreationRepairPriorOperation;
  getCreationRepairAncestorIds: GetCreationRepairAncestorIdsOperation;
  verifyUnknownRepairChain: VerifyUnknownRepairChainOperation;
  getCreationRepair: GetCreationRepairOperation;
  claimCreationRepair: ClaimCreationRepairOperation;
  completeCreationRepair: CompleteCreationRepairOperation;
  getCurrent: GetCurrentOperation;
  getManifestForJob: GetManifestForJobOperation;
  history: HistoryOperation;
}
