import {
  type NativeShortBinding,
  createNativeShortMetadataSnapshot,
  NATIVE_SHORT_HASH_BASES,
} from '../../src/platform/short-native-metadata.js';

import {
  type NativeShortBodyParagraphInput,
  type NativeShortBodyTrialPolicy,
  type NativeShortBodySnapshot,
  createNativeShortBodySnapshot,
  type NativeShortBodyWriteRequest,
  NATIVE_SHORT_BODY_REPRESENTATION,
  NativeShortBodyError,
  planNativeShortBodyUpdate,
  nativeShortBodyDesiredContentHash,
  validateNativeShortBodyPlan,
  assertNativeShortBodyPreSave,
  compareNativeShortBodyReadback,
} from '../../src/platform/short-native-body.js';

import { bodyOracle0 } from './body-oracle-entities-and-terminal-breaks.js';

import { bodyOracle1 } from './body-oracle-trial-marker-boundaries.js';

import { bodyOracle2 } from './body-oracle-append-and-existing-marker.js';

import assert from 'node:assert/strict';

import { createHash } from 'node:crypto';

// These complete synthetic literals come from the independent frozen oracle.md.
// No expected HTML/vector/hash is generated by the new domain implementation.
export interface RawFixture {
  binding: NativeShortBinding;
  editData: Record<string, unknown>;
  categoryData: Record<string, unknown>;
}

interface OracleCase {
  id: string;
  sourceHtml: string;
  sourceVector: readonly NativeShortBodyParagraphInput[];
  submittedParagraphs: readonly NativeShortBodyParagraphInput[];
  trial: NativeShortBodyTrialPolicy;
  expected: {
    desiredHtml: string;
    effectiveWireLines: readonly (readonly string[])[];
    appendedWireTerminal: boolean;
    marker: {
      count: number;
      boundary: number | null;
      prefixCharacterCount?: number;
      characterCount?: number;
      eligibleParagraphCount?: number;
      percentage?: string;
      displayPercent?: number;
      class?: string;
      rawHtml?: string;
      anchorSourceIndex?: number;
    };
    exactHtmlUtf8Sha256: string;
    writePlan: { outcome: string; fixedCode: string | null; formGenerated: boolean };
  };
  notes: string;
}

const BASE: RawFixture = {
  binding: {
    account: {
      kind: 'account_id',
      id: '9001',
    },
    work: {
      kind: 'short',
      id: '7000000001',
    },
  },
  editData: {
    item_id: '7000000001',
    publish_status: 0,
    multi_title: ['Synthetic title', 'Synthetic tail'],
    content: '<replace with each literal sourceHtml>',
    thumb_uri: 'synthetic-head-uri',
    book_thumb_uri: 'synthetic-cover-uri',
    category: [
      {
        category_id: 'c2',
        label: 'B',
        name: 'Second',
      },
      {
        category_id: 'c1',
        label: 'A',
        name: 'First',
      },
    ],
    category_max_count: 8,
    sign_type: 1,
    origin_activity_flag: 0,
    latest_version: 7,
    modify_time: '1789450000',
    opaque: {
      keep: [null, true, 'synthetic-original'],
    },
  },
  categoryData: {
    category_list: [
      {
        category_id: 'c1',
        label: 'A',
        name: 'First',
      },
      {
        category_id: 'c2',
        label: 'B',
        name: 'Second',
      },
    ],
    opaque_catalog: 'synthetic-catalog-original',
  },
};

export const ORACLE: readonly OracleCase[] = [...bodyOracle0, ...bodyOracle1, ...bodyOracle2];

const BASE_FORM = {
  item_id: '7000000001',
  content: '<each case desiredHtml>',
  thumb_uri: 'synthetic-head-uri',
  book_thumb_uri: 'synthetic-cover-uri',
  item_version: '-1',
  multi_title: '["Synthetic title","Synthetic tail"]',
  sign_type: '1',
  activity_flag: '0',
  category: 'c2,c1',
};

export const GOLDEN_CANONICAL =
  '{"basis":"native-short-body-full-source-except-content-and-exact-server-revision-fields/v1","binding":{"account":{"id":"9001","kind":"account_id"},"work":{"id":"7000000001","kind":"short"}},"categoryData":{"category_list":[{"category_id":"c1","label":"A","name":"First"},{"category_id":"c2","label":"B","name":"Second"}],"opaque_catalog":"synthetic-catalog-original"},"editData":{"book_thumb_uri":"synthetic-cover-uri","category":[{"category_id":"c2","label":"B","name":"Second"},{"category_id":"c1","label":"A","name":"First"}],"category_max_count":8,"item_id":"7000000001","multi_title":["Synthetic title","Synthetic tail"],"opaque":{"10":10,"2":2,"é":3,"é":4,"𐀀":7,"😀":5,"":6},"origin_activity_flag":0,"publish_status":0,"sign_type":1,"thumb_uri":"synthetic-head-uri"},"scope":"short-native-body/v1"}';

export const GOLDEN_PRESERVATION_SHA =
  'cbbd42ddb6975afb128c81f84c668d08baa9ab538cc4e8946725970b8062e64e';

export function fixture(content: string, mutate?: (raw: RawFixture) => void): RawFixture {
  const raw = structuredClone(BASE);
  raw.editData.content = content;
  mutate?.(raw);
  return raw;
}

export function snapshot(
  content: string,
  mutate?: (raw: RawFixture) => void,
): NativeShortBodySnapshot {
  return createNativeShortBodySnapshot(createNativeShortMetadataSnapshot(fixture(content, mutate)));
}

export function request(
  before: NativeShortBodySnapshot,
  paragraphs?: readonly NativeShortBodyParagraphInput[],
  trial: NativeShortBodyTrialPolicy = { action: 'preserve' },
): NativeShortBodyWriteRequest {
  return {
    expectedSnapshotVersionHash: before.snapshotVersionHash,
    hashBasis: NATIVE_SHORT_HASH_BASES.snapshot,
    expectedState: 'draft',
    representation: NATIVE_SHORT_BODY_REPRESENTATION,
    paragraphs:
      paragraphs ??
      before.sourceParagraphs.map((p) => ({ sourceIndex: p.sourceIndex, lines: [...p.lines] })),
    trial,
  };
}

export function after(
  before: NativeShortBodySnapshot,
  html: string,
  mutate?: (raw: RawFixture) => void,
): NativeShortBodySnapshot {
  const raw: RawFixture = {
    binding: before.binding,
    editData: structuredClone(before.native.editData),
    categoryData: structuredClone(before.native.categoryData),
  };
  raw.editData.content = html;
  raw.editData.latest_version = Number(before.native.editData.latest_version) + 1;
  raw.editData.modify_time = '1789450001';
  mutate?.(raw);
  return createNativeShortBodySnapshot(createNativeShortMetadataSnapshot(raw));
}

export function rejected(run: () => unknown, code?: string): void {
  assert.throws(
    run,
    (error) =>
      error instanceof NativeShortBodyError &&
      (!code || error.code === code) &&
      error.message === `Native short body rejected: ${error.code}`,
  );
}

export function checkOracle(index: number): void {
  const o = ORACLE[index]!,
    before = snapshot(o.sourceHtml),
    r = request(before, o.submittedParagraphs, o.trial);
  assert.deepEqual(
    before.sourceParagraphs.map((p) => ({ sourceIndex: p.sourceIndex, lines: p.lines })),
    o.sourceVector,
  );
  assert.equal(
    createHash('sha256').update(o.expected.desiredHtml, 'utf8').digest('hex'),
    o.expected.exactHtmlUtf8Sha256,
  );
  if (o.expected.writePlan.outcome === 'reject') {
    assert.equal(o.expected.writePlan.formGenerated, false);
    rejected(() => planNativeShortBodyUpdate(before, r), o.expected.writePlan.fixedCode!);
    return;
  }
  const plan = planNativeShortBodyUpdate(before, r),
    expected = o.expected;
  assert.equal(plan.expectation.desiredHtml, expected.desiredHtml);
  assert.equal(plan.expectation.expectedDocumentHash, expected.exactHtmlUtf8Sha256);
  assert.equal(plan.expectation.appendedWireTerminal, expected.appendedWireTerminal);
  assert.deepEqual(
    plan.expectation.effectiveWireParagraphs.map((p) => p.lines),
    expected.effectiveWireLines,
  );
  assert.equal(plan.expectation.marker.boundary, expected.marker.boundary);
  assert.equal(plan.expectation.marker.rawHtml === null ? 0 : 1, expected.marker.count);
  if (expected.marker.rawHtml !== undefined)
    assert.equal(plan.expectation.marker.rawHtml, expected.marker.rawHtml);
  if (expected.marker.class !== undefined)
    assert.equal(plan.expectation.marker.attrs!.class, expected.marker.class);
  if (expected.marker.percentage !== undefined)
    assert.equal(plan.expectation.marker.attrs!['data-percentage'], expected.marker.percentage);
  assert.deepEqual(plan.form, { ...BASE_FORM, content: expected.desiredHtml });
  assert.equal(Object.hasOwn(plan.form, 'use_ai'), false);
  assert.equal(Object.hasOwn(plan.form, 'description'), false);
  assert.equal(plan.request.method, 'POST');
  assert.equal(plan.atomicRevision, false);
  assert.equal(new URLSearchParams(plan.request.body).get('content'), expected.desiredHtml);
  assert.equal(
    plan.desiredContentHash,
    nativeShortBodyDesiredContentHash({ expectation: plan.expectation, form: plan.form }),
  );
  assert.deepEqual(validateNativeShortBodyPlan(JSON.parse(JSON.stringify(plan))), plan);
  assertNativeShortBodyPreSave(before, plan);
  const observed = after(before, expected.desiredHtml),
    comparison = compareNativeShortBodyReadback(
      JSON.parse(JSON.stringify(plan.expectation)),
      observed,
    );
  assert.equal(comparison.reason, 'match');
  assert.equal(comparison.matches, true);
  assert.equal(observed.observedWireVectorHash, plan.expectation.effectiveWireVectorHash);
  assert.equal(Object.hasOwn(observed, 'appendedWireTerminal'), false);
  assert.equal(Object.isFrozen(plan.expectation.effectiveWireParagraphs), true);
  if (expected.marker.characterCount !== undefined)
    assert.equal(observed.document.characterCount, expected.marker.characterCount);
  if (expected.marker.prefixCharacterCount !== undefined)
    assert.equal(observed.document.prefixCharacterCount, expected.marker.prefixCharacterCount);
  if (expected.marker.eligibleParagraphCount !== undefined)
    assert.equal(observed.document.eligibleParagraphCount, expected.marker.eligibleParagraphCount);
  if (expected.marker.displayPercent !== undefined)
    assert.equal(observed.document.displayPercent, expected.marker.displayPercent);
}
