export { FANQIE_ORIGIN } from './reads/fanqie-origin.js';
export { SHORT_WORKS_URL } from './reads/fanqie-origin.js';
export { SHORT_METRICS_URL } from './reads/fanqie-origin.js';
export { LONG_WORKS_URL } from './reads/fanqie-origin.js';
export { LONG_METRICS_URL } from './reads/fanqie-origin.js';
export type { DatasetStatus } from './reads/fanqie-origin.js';
export type { DatasetError } from './reads/fanqie-origin.js';
export type { DatasetCoverage } from './reads/fanqie-origin.js';
export type { ChapterVolumeRefreshEvent } from './reads/fanqie-origin.js';
export type { ChapterVolumeRefreshDiagnostic } from './reads/fanqie-origin.js';
export type { CurrentChapterObservedReason } from './reads/fanqie-origin.js';
export type { CurrentChapterRejectedCheckSite } from './reads/fanqie-origin.js';
export type { CurrentChapterRejectedCheckPredicate } from './reads/fanqie-origin.js';
export type { CurrentChapterCanonicalBootstrapDiagnostic } from './reads/fanqie-origin.js';
export type { CurrentChapterSourceFamily } from './reads/fanqie-origin.js';
export type { CurrentChapterSourceClearReason } from './reads/fanqie-origin.js';
export type { CurrentChapterSourceOutcome } from './reads/fanqie-origin.js';
export type { CurrentChapterSourceCounts } from './reads/fanqie-origin.js';
export type { CurrentChapterSourceRequestObservation } from './reads/fanqie-origin.js';
export type { CurrentChapterSourceClearObservation } from './reads/fanqie-origin.js';
export type { CurrentChapterSourceObservation } from './reads/fanqie-origin.js';
export type { CurrentChapterCollectionFailureDiagnostic } from './reads/is-metrics-dataset.js';
export type { ChapterManagementCoverage } from './reads/is-metrics-dataset.js';
export type { ChapterManagementControlObservation } from './reads/is-metrics-dataset.js';
export type { StatisticsWindowUnknown } from './reads/is-metrics-dataset.js';
export type { StatisticsTimezoneUnknown } from './reads/is-metrics-dataset.js';
export { isMetricsDataset } from './reads/is-metrics-dataset.js';
export { projectMetricTimeContext } from './reads/is-metrics-dataset.js';
export type { DatasetResult } from './reads/is-metrics-dataset.js';
export { PlatformReadError } from './reads/make-dataset.js';
export { makeDataset } from './reads/make-dataset.js';
export { numberOrNull } from './reads/make-dataset.js';
export { identifierOrNull } from './reads/make-dataset.js';
export { parseVisibleStatistics } from './reads/make-dataset.js';
export { normalizeShortStatus } from './reads/make-dataset.js';
export type { ReadOptions } from './reads/make-dataset.js';
export type { ReadResponseStructure } from './reads/make-dataset.js';
export { isChapterReadSchemaSource } from './reads/make-dataset.js';
export { isReadSchemaSource } from './reads/make-dataset.js';
export { projectReadResponseFields } from './reads/project-read-response-fields.js';
export { inspectPageAccess } from './reads/project-read-response-fields.js';
export type { ShortWork } from './reads/project-read-response-fields.js';
export { collectShortWorks } from './reads/collect-short-works.js';
export type { ShortMetric } from './reads/collect-short-works.js';
export { collectShortMetrics } from './reads/discard-changed-document.js';
export type { EvidenceField } from './reads/discard-changed-document.js';
export type { CollectionEvidenceProfile } from './reads/discard-changed-document.js';
export type { ProfileReadOptions } from './reads/discard-changed-document.js';
export { validateReadProfile } from './reads/discard-changed-document.js';
export { collectWithProfile } from './reads/collect-with-profile.js';
export type { LongWork } from './reads/collect-with-profile.js';
export { collectLongWorks } from './reads/collect-long-works-api.js';
export type { ChapterRecord } from './reads/collect-long-works-api.js';
export type { ChapterVolume } from './reads/collect-long-works-api.js';
export type { ChapterVolumeInventory } from './reads/collect-long-works-api.js';
export type { ChapterApiEvidencePlan } from './reads/collect-long-works-api.js';
export type { ChapterDraftRecord } from './reads/collect-long-works-api.js';
export { parseChapterDraftPage } from './reads/parse-chapter-draft-page.js';
export type { ChapterReadOptions } from './reads/parse-chapter-draft-page.js';
export { parseChapterPage } from './reads/parse-chapter-draft-page.js';
export { parseCurrentChapterVolumes } from './reads/parse-chapter-draft-page.js';
export { verifyCurrentChapterBook } from './reads/parse-chapter-draft-page.js';
export { parseCandidateChapterVolumes } from './reads/parse-chapter-draft-page.js';
export { collectChapters } from './reads/collect-chapters-api.js';
export type { LongMetric } from './reads/parse-platform-update-time.js';
export { parsePlatformUpdateTime } from './reads/parse-platform-update-time.js';
export { collectLongMetrics } from './reads/collect-long-metrics.js';
