export type { PlatformState } from './writes/hash-draft-content.js';
export type { WriteCapability } from './writes/hash-draft-content.js';
export type { WriteTarget } from './writes/hash-draft-content.js';
export type { Selector } from './writes/hash-draft-content.js';
export type { ReadField } from './writes/hash-draft-content.js';
export type { FieldBinding } from './writes/hash-draft-content.js';
export type { SubmissionStep } from './writes/hash-draft-content.js';
export type { UiWriteProfile } from './writes/hash-draft-content.js';
export type { UploadReference } from './writes/hash-draft-content.js';
export type { DraftMetadata } from './writes/hash-draft-content.js';
export type { DraftContent } from './writes/hash-draft-content.js';
export type { WriteSnapshot } from './writes/hash-draft-content.js';
export type { GenericShortOwnerInvocation } from './writes/hash-draft-content.js';
export type { GenericShortEditorProof } from './writes/hash-draft-content.js';
export type { ModernShortSnapshot } from './writes/hash-draft-content.js';
export type { DraftSnapshot } from './writes/hash-draft-content.js';
export type { GenericShortObservation } from './writes/hash-draft-content.js';
export type { WriteOptions } from './writes/hash-draft-content.js';
export type { UpdateDraftInput } from './writes/hash-draft-content.js';
export type { CreateDraftInput } from './writes/hash-draft-content.js';
export type { UpdateMetadataInput } from './writes/hash-draft-content.js';
export type { SaveChapterInput } from './writes/hash-draft-content.js';
export type { CreateChapterInput } from './writes/hash-draft-content.js';
export type { PreparedSubmission } from './writes/hash-draft-content.js';
export type { SubmitInput } from './writes/hash-draft-content.js';
export type { WriteResult } from './writes/hash-draft-content.js';
export { PlatformWriteError } from './writes/hash-draft-content.js';
export { normalizeBody } from './writes/hash-draft-content.js';
export { hashDraftContent } from './writes/hash-draft-content.js';
export { isGenericShortCaptureFailure } from './writes/is-generic-short-capture-failure.js';
export { isModernShortSnapshot } from './writes/is-generic-short-capture-failure.js';
export { validateGenericShortSnapshot } from './writes/is-generic-short-capture-failure.js';
export { readWriteSnapshot } from './writes/await-created-short-target.js';
export { updateDraft } from './writes/click-short-save-with-acknowledgement.js';
export { updateWorkMetadata } from './writes/click-short-save-with-acknowledgement.js';
export { saveChapterDraft } from './writes/click-short-save-with-acknowledgement.js';
export { createDraft } from './writes/click-short-save-with-acknowledgement.js';
export { createChapterDraft } from './writes/click-short-save-with-acknowledgement.js';
export { prepareSubmission } from './writes/create-target.js';
export { submitShortStory } from './writes/submit.js';
export { publishChapter } from './writes/submit.js';
export { reconcileWrite } from './writes/submit.js';
export { getWriteCapabilities } from './writes/submit.js';
export type { EditorDiagnosticInput } from './writes/submit.js';
export type { EditorDiagnostic } from './writes/submit.js';
export { diagnoseEditor } from './writes/diagnostic-url.js';
export type { LongBookMetadataTarget } from './writes/diagnostic-url.js';
export type { UiLongBookMetadataProfile } from './writes/diagnostic-url.js';
export type { LongBookMetadataSnapshot } from './writes/diagnostic-url.js';
export type { LongBookMetadataOptions } from './writes/diagnostic-url.js';
export type { LongBookMetadataInput } from './writes/diagnostic-url.js';
export type { LongBookMetadataResult } from './writes/diagnostic-url.js';
export { hashLongBookMetadata } from './writes/book-target.js';
export { readLongBookMetadataSnapshot } from './writes/book-target.js';
export { updateLongBookMetadata } from './writes/update-long-book-metadata.js';
export { getLongBookMetadataCapabilities } from './writes/update-long-book-metadata.js';
